### ISSUE TITLE
Quiet output when generating image

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-api#10]
Docker image generation results in a 48MB log file. Commands like tar can be made less verbose to shrink this substantially.

**Comment by cbaakman** [comment]
I removed the -v flags from tar. It should give less output now.

**Comment by cbaakman** [comment]
Also, wget produces a lot of output. I added the -nv flag to make it give less output.

**Comment by jonblack** [comment]
Have these changes been committed?
